# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: J.A. Simmons V
email: abuse@jasimmonsv.com
description: > # this means to ignore newlines until "baseurl:"
  The life and builds of J.A. Simmons V.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jasimmonsv.com" # the base hostname & protocol for your site
twitter_username: jasimmonsv
github_username:  jasimmonsv
instagram_username: jasimmonsv

# Build settings
markdown: kramdown
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
#Config settings you cannot change
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
